<html>
	<head>
		<title></title>
		<link rel="stylesheet" href="./assets/css/style.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		
		<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	</head>
	<?php require('init.php'); ?>
	<body>
		<div class="masthead clearfix">
            <div class="inner col-md-8">
              <h3 class="masthead-brand">David Humberto González Calvillo</h3>
            </div>
            <div class="col-md-4">

            </div>
          </div>
		<div class="col-lg-12 col-md-12 col-sm-12">
				

			<ul class="nav nav-tabs" id="myTab" role="tablist">
			  <li class="nav-item">
			    <a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="description" aria-selected="true">Description</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" id="ex1-tab" data-toggle="tab" href="#ex1" role="tab" aria-controls="ex1" aria-selected="false">Exercise #1</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" id="ex2-tab" data-toggle="tab" href="#ex2" role="tab" aria-controls="ex2" aria-selected="false">Exercise #2</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#ex3" role="tab" aria-controls="ex3" aria-selected="false">Exercise #3</a>
			  </li>

			</ul>
			<div class="tab-content" id="myTabContent">
			  <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
			  	<h1>Description:</h1>
				<p>The next site, is to show my skills regarding with the next excercises:</p>
				<ul>
					<li>
						 "Print out the odd numbers between 1 and 100"
					</li>
					<li>
						"Give an array of unsorted integers, print out the sum of the two largest values without using array sort"
					</li>
					<li>
						"Given two strings of different lengths, find the longest overlap" For example, House and Mouse would return the integer 4 because ouse overlaps”
					</li>
				</ul>
			  </div>
			  <div class="tab-pane fade" id="ex1" role="tabpanel" aria-labelledby="ex1-tab">
				<h1>Exercise 1:</h1> 
				<h3>"Print out the odd numbers between 1 and 100".</h3>
				
					<div class="excercise-div col-md-12">
						<div class="numbers-div">
							<?php 
								foreach ( $numbers as $index => $number ) {
									echo ($index == ($totalNumbers)) ?  $number . '.' : $number . ' -> ';
								}
							?>
						</div>
					</div>
					
					
			  </div>
			  <div class="tab-pane fade" id="ex2" role="tabpanel" aria-labelledby="ex2-tab">
				<h1>Exercise 2:</h1> 
				<h3>"Give an array of unsorted integers, print out the sum of the two largest values without using array sort"</h3>
				<p>*The array is autogenerated by the method fillArray on the class UnsortedIntegers, and this function is called on the class contructor, there, it's defined the size of the array by a random function from 5 to 20, also the min and max numbers that the element of an array can take. </p>
				<div class="excercise-div col-md-12">
					<p><b>Sum of largest values : </b> <?php echo $sumUnsortedNumbers; ?></p>
					<p><b>Max numbers : </b> <?php echo implode(", ", $maxUnsortedNumbers); ?></p>
					<b>List of array:</b>
					<ul>
						<?php 
							foreach($listUnsortedNumbers as $index => $value) {
								echo "<li> " . $value . "</li>";
							}
						?>
					</ul>
				</div>
			  </div>
			  <div class="tab-pane fade" id="ex3" role="tabpanel" aria-labelledby="ex3-tab">
				<h1>Exercise 3:</h1>
				<h3>"Given two strings of different lengths, find the longest overlap" For example, House and Mouse would return the integer 4 because ouse overlaps"</h3>
				<p>*This excercise uses ajax method to post the data to backend and get the result, you can see assets/js/functions.js to see the method used.</p>
					<div id="resultOverlap" class="alert">
						
					</div>

					<div class="form-group row">
					  <label for="firstString" class="col-2 col-form-label">First String:</label>
					  <div class="col-6">
					    <input class="form-control" name="firstString" type="text" id="firstString" value="ferrocarril">
					  </div>
					</div>
					<div class="form-group row">
					  <label for="secondString" class="col-2 col-form-label">second String:</label>
					  <div class="col-6">
					    <input class="form-control" name="secondString" type="text" id="secondString" value="carrilero">
					  </div>
					</div>
					<button class="btn btn-success" id="compareStrings">Compare Strings</button>
					
					
			  </div>
			</div>

		</div>

		<script type="text/javascript" src="./assets/js/functions.js"></script>
	</body>
</html>